import { Car } from './types';

export const mockCars: Car[] = [
  {
    id: 1,
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 28500,
    mileage: 15000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Silver',
    images: ['/images/toyota-camry-1.jpg', '/images/toyota-camry-2.jpg'],
    description: 'Well-maintained Camry with excellent fuel economy. Perfect daily driver with low miles and clean title.',
    features: ['Bluetooth', 'Backup Camera', 'Lane Assist', 'Cruise Control', 'Keyless Entry'],
    vin: '1HGCM82633A123456',
  },
  {
    id: 2,
    make: 'Honda',
    model: 'Civic',
    year: 2021,
    price: 24900,
    mileage: 22000,
    transmission: 'CVT',
    fuelType: 'Gasoline',
    color: 'Black',
    images: ['/images/honda-civic-1.jpg', '/images/honda-civic-2.jpg'],
    description: 'Sporty and reliable Honda Civic in excellent condition. Great fuel efficiency and modern tech features.',
    features: ['Apple CarPlay', 'Android Auto', 'Sunroof', 'Heated Seats', 'Push-to-Start'],
    vin: '2HGFC2F53MH543210',
  },
  {
    id: 3,
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 42500,
    mileage: 8000,
    transmission: 'Automatic',
    fuelType: 'Electric',
    color: 'White',
    images: ['/images/tesla-model3-1.jpg', '/images/tesla-model3-2.jpg'],
    description: 'Like-new Tesla Model 3 with Autopilot and Full Self-Driving capability. One owner with full service history.',
    features: ['Autopilot', '15-inch Touchscreen', 'Premium Audio', 'Heated Seats', 'Navigation', 'Supercharging Enabled'],
    vin: '5YJ3E1EBJPF123456',
  },
  {
    id: 4,
    make: 'Ford',
    model: 'F-150',
    year: 2020,
    price: 35000,
    mileage: 45000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Blue',
    images: ['/images/ford-f150-1.jpg', '/images/ford-f150-2.jpg'],
    description: 'Powerful Ford F-150 truck ready for work or play. Towing package installed and well-maintained.',
    features: ['Towing Package', '4WD', 'Bed Liner', 'Trailer Brake Controller', 'Sync 3 Infotainment'],
    vin: '1FTEW1EP4LF987654',
  },
  {
    id: 5,
    make: 'BMW',
    model: '3 Series',
    year: 2022,
    price: 42000,
    mileage: 18000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Gray',
    images: ['/images/bmw-3series-1.jpg', '/images/bmw-3series-2.jpg'],
    description: 'Luxurious BMW 3 Series in pristine condition. Premium package with all the bells and whistles.',
    features: ['Leather Interior', 'Navigation', 'Harman Kardon Audio', 'Heated/Ventilated Seats', 'Moonroof', 'M Sport Package'],
    vin: 'WBA8E9C52MFD789012',
  },
  {
    id: 6,
    make: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    price: 32000,
    mileage: 12000,
    transmission: 'CVT',
    fuelType: 'Hybrid',
    color: 'Red',
    images: ['/images/toyota-rav4-1.jpg', '/images/toyota-rav4-2.jpg'],
    description: 'Eco-friendly RAV4 Hybrid with excellent MPG. AWD capability perfect for all weather conditions.',
    features: ['AWD', 'Panoramic Roof', 'JBL Audio', 'Heated Steering Wheel', 'Qi Wireless Charging', 'Birds Eye Camera'],
    vin: '2T3BWRFV8PW345678',
  },
  {
    id: 7,
    make: 'Chevrolet',
    model: 'Corvette',
    year: 2021,
    price: 68000,
    mileage: 9500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Yellow',
    images: ['/images/chevy-corvette-1.jpg', '/images/chevy-corvette-2.jpg'],
    description: 'Stunning C8 Corvette in striking yellow color. Garage kept and babied by original owner.',
    features: ['8-Speed Dual-Clutch', 'Performance Exhaust', 'Front Lift System', 'Bose Performance Audio', 'Navigation', 'Performance Data Recorder'],
    vin: '1G1Y2D0H8M5123456',
  },
  {
    id: 8,
    make: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    price: 27500,
    mileage: 28000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'White',
    images: ['/images/hyundai-tucson-1.jpg', '/images/hyundai-tucson-2.jpg'],
    description: 'Practical and stylish Tucson SUV with great safety ratings. Perfect family vehicle.',
    features: ['Blind Spot Detection', 'Forward Collision Warning', 'Lane Keep Assist', 'Apple CarPlay', 'Android Auto', 'Hands-free Hatch'],
    vin: 'KM8J33CA5NU654321',
  },
];
